version: '3.8'

services:
  users-db:
    container_name: users-db
    build: project/db
    environment:
      - MYSQL_ROOT_PASSWORD=root123
    healthcheck:
      test: exit 0
  users-service:
    container_name: users-services
    build: services/users
    expose:
      - 5000
    environment:
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=mysql+pymysql://root:root123@users-db:3306/users_prod
      - DATABASE_TEST_URL=mysql+pymysql://root:root123@users-db:3306/users_test
    command: gunicorn -b 0.0.0.0:5000 manage:app
    depends_on:
      - users-db
    links:
      - users-db
  nginx:
    container_name: nginx
    build: ./nginx/
    restart: always
    ports:
      - 80:80  # 端口暴露（主机端口：容器端口）
    depends_on:
      - users-service
    links:
      - users-service
